#!/bin/bash

FLASH_TOOL_BIN=./tools/linux/Linux_Upgrade_Tool/Linux_Upgrade_Tool/upgrade_tool

#IMAGE_DIR=IMAGE/RV1126-OPENHD_20220204.1550_RELEASE_TEST
MOST_RECENT_IMAGE_OUTPUT_DIR=$(ls IMAGE/ -Art | tail -n 1)

MOST_RECENT_IMAGE_OUTPUT_DIR_FILE=IMAGE/$MOST_RECENT_IMAGE_OUTPUT_DIR/IMAGES/update.img


echo "Flasing update.img from $MOST_RECENT_IMAGE_OUTPUT_DIR_FILE"


sudo $FLASH_TOOL_BIN uf $MOST_RECENT_IMAGE_OUTPUT_DIR_FILE